# -*- coding: utf-8 -*-
"""RotateImage.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D6D-GATtytQmuXPE92d8WL6lr0dvu1Wy
"""

import cv2
import imutils
import numpy as np

img = cv2.imread('dataset/User.1.1.jpg',0)

# grab the dimensions of the image and calculate the center
# of the image
(h, w) = img.shape[:2]
center = (w / 2, h / 2)
# rotate the image by 180 degrees
for angle in np.arange(0, 360, 15):
  M = cv2.getRotationMatrix2D(center, angle, 1.0)
  rotated = cv2.warpAffine(img, M, (w, h))
  cv2.imshow("rotated", rotated)
  cv2.waitKey(0)
# print(img.shape)

# img_rotate_90_clockwise = cv2.rotate(img, cv2.ROTATE_90_CLOCKWISE)
# cv2.imshow('', img_rotate_90_clockwise)
# cv2.waitKey(1)

# for angle in np.arange(0, 360, 15):
#   rotated = imutils.rotate_bound(img, angle)
#   cv2.imshow('', rotated)
#   cv2.waitKey(1)
#   #cv2.imwrite('User.2.30.'+str(angle)+'.jpg',rotated) ##kanggo save .-.

# for angle in np.arange(0, 360, 15):
#   rotated = imutils.rotate(img, angle)
#   cv2.imshow('', rotated)
#   cv2.waitKey(1)